using System;
using System.Collections.Generic;

namespace RandomUser.Core.Infrastructure
{
    internal class StaticSeedDataStore : ISeedDataStore
    {
        public IEnumerable<string> Titles() => _titles;

        public IEnumerable<string> FirstNames() => _firstNames;

        public IEnumerable<string> LastNames() => _lastNames;



        private readonly string[] _titles = {"Mr", "Dr", "Sir"};

        private readonly string[] _firstNames = {
            "Alex",
            "Alexander",
            "Ari",
            "Ariki",
            "Charlie",
            "Ethan",
            "George",
            "Hunter",
            "Jack",
            "Jackson",
            "James",
            "Josh",
            "Jaxon",
            "Jaxson",
            "Kauri",
            "Leo",
            "Lucas",
            "Manaia",
            "Mason",
            "Mateo",
            "Mikaere",
            "Nikau",
            "Noah",
            "Oliver",
            "Rawiri",
            "Taika",
            "Te Ariki",
            "Thomas",
            "William"
        };

        private readonly string[] _lastNames = {
            "Adams",
            "Allan",
            "Allard",
            "Anderson",
            "Armstrong",
            "Baker",
            "Bell",
            "Bennett",
            "Boone",
            "Brown",
            "Burns",
            "Campbell",
            "Carter",
            "Chen",
            "Clark",
            "Clarke",
            "Collins",
            "Cook",
            "Cooper",
            "Cox",
            "Davies",
            "Davis",
            "Donovan",
            "Duncan",
            "Edwards",
            "Ferguson",
            "Fraser",
            "Gray",
            "Green",
            "Greenwood",
            "Hall",
            "Harris",
            "Hart",
            "Henderson",
            "Hill",
            "Hodgson",
            "Hogan",
            "Holmes",
            "Huang",
            "James",
            "Johnson",
            "Johnston",
            "Jones",
            "Kelly",
            "Kim",
            "King",
            "Kumar",
            "Lee",
            "Li",
            "Lin",
            "Martin",
            "Matthews",
            "McDonald",
            "Mills",
            "Mitchell",
            "Moore",
            "Murphy",
            "Murray",
            "Nguyen",
            "Parker",
            "Patel",
            "Phillips",
            "Reid",
            "Richardson",
            "Roberts",
            "Robertson",
            "Robinson",
            "Rutherford",
            "Ryan",
            "Scott",
            "Shaw",
            "Shepherd",
            "Simpson",
            "Singh",
            "Smith",
            "Stewart",
            "Tan",
            "Taylor",
            "Thomas",
            "Thompson",
            "Thomson",
            "Thomson",
            "Thomson",
            "Turner",
            "Walker",
            "Wang",
            "Ward",
            "Watson",
            "White",
            "Williams",
            "Wilson",
            "Wong",
            "Wright",
            "Wu",
            "Xu",
            "Yang",
            "Young",
            "Zhang",
            "Zhou"
        };
    }
}
